name: Build Dev Container

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile.dev'
      - '.github/workflows/devcontainer.yml'
      - 'godot-cpp/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile.dev'
      - 'godot-cpp/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare tags
        id: prep
        run: |
          REPO=ghcr.io/${{ github.repository_owner }}/addon_tiny_lobby_client-dev
          echo "repo=$REPO" >> $GITHUB_OUTPUT
          if [[ "${{ github.ref }}" == refs/heads/main ]]; then
            echo "tag=main" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.dev
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.prep.outputs.repo }}:${{ steps.prep.outputs.tag }}
          cache-from: type=registry,ref=${{ steps.prep.outputs.repo }}:buildcache
          cache-to: type=registry,ref=${{ steps.prep.outputs.repo }}:buildcache,mode=max
